name: Print Hello World
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Printing Hello World
        uses: "./actions/"
    env:
      deployment_env: "This comes from deploy.yml file"
      github_secret: ${{ secrets.USERNAME }}
